# Generated by Django 3.1 on 2020-09-19 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.TextField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField()),
                ('cover_image', models.ImageField(default='book-cover.png', upload_to='book_covers', verbose_name="Upload the book's cover here")),
                ('file_upload', models.FileField(upload_to='books', verbose_name='Upload the book here')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_edit', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Select some tags for this book', to='resources.Tag')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
