# Generated by Django 3.1.6 on 2021-02-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('resources', '0002_auto_20210211_0756'),
    ]

    database_operations = [
        migrations.AlterModelTable('Video', 'videos_video')
    ]

    state_operations = [
        migrations.DeleteModel('Video')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
