name: Production Deploy

on:
  pull_request:
    branches: [main, prod]
    types:
      - closed

  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install

    - name: Authenticate gcloud
      run: |
        chmod +x ./scripts/decrypt_secret.sh
        ./scripts/decrypt_secret.sh
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ./secrets/raw/${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
        SECRET_FILE: ${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
        SECRET_FILE_PASSPHRASE: ${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE_PASSPHRASE}}

    - name: Deploy to App Engine Standard
      run: |
        pipenv run python manage.py collectstatic --no-input
        chmod +x ./scripts/deploy_to_app_engine.sh
        ./scripts/deploy_to_app_engine.sh
      env:
        # Important
        DJANGO_SETTINGS_MODULE: config.settings.production

        ADMINS: ${{secrets.ADMINS}}
        ADMIN_URL: ${{secrets.ADMIN_URL}}
        ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}

        DATABASE_INSTANCE_CONNECTION_NAME: ${{secrets.DATABASE_INSTANCE_CONNECTION_NAME}}
        DATABASE_URL: ${{secrets.DATABASE_URL}}
        DB_ENGINE: ${{secrets.DB_ENGINE}}
        DB_NAME: ${{secrets.DB_NAME}}
        DB_USER: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}

        DJANGO_DEBUG: ${{secrets.DJANGO_DEBUG}}
        DJANGO_EMAIL_HOST_USER: ${{secrets.DJANGO_EMAIL_HOST_USER}}
        DJANGO_EMAIL_HOST_PASSWORD: ${{secrets.DJANGO_EMAIL_HOST_PASSWORD}}
        DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}

        GCP_STORAGE_BUCKET_NAME: ${{secrets.GCP_STORAGE_BUCKET_NAME}}
        GOOGLE_APPLICATION_CREDENTIALS: ./secrets/raw/${{secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_FILE}}
        GOOGLE_CLOUD_PROJECT: ${{secrets.GOOGLE_CLOUD_PROJECT}}
        GOOGLE_ANALYTICS_ID: ${{secrets.GOOGLE_ANALYTICS_ID}}
